# Generated by Django 3.2.3 on 2022-11-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoapp', '0003_auto_20221102_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='password', max_length=20),
        ),
    ]
